### ISSUE TITLE
pre-commit cannot find built-in templates

### ISSUE THREAD

**Issue by liyishuai** [johann-petrak/licenseheaders#66]
Here's my `.pre-commit-config.yaml`:
```yaml
---
repos:
  - repo: https://github.com/johann-petrak/licenseheaders.git
    rev: 'aef25543567a9db59448349127260e386619cbf2'
    hooks:
      - id: licenseheaders
        args: ["-t", "mpl-2", "-cy", "-f"]
```

Error message:
```
licenseheaders...........................................................Failed
- hook id: licenseheaders
- exit code: 1

licenseheaders_0.8.8 ERROR: Not a built-in template and not a file, cannot proceed: mpl-2
licenseheaders_0.8.8 ERROR: Built in templates:

```

Executing `licenseheaders` in command line worked fine.
